### ISSUE TITLE
no courses show up in My mindmap overview block: "mymindmap_overview_no_courses"

### ISSUE THREAD

**Issue by francescor** [deedey/moodle-block_mymindmap_overview#1]
Hi
we've just installed it in a recently upgraded Moodle 4.x but we only see "mymindmap_overview_no_courses" in the block

how to debug it? (we have plenty of courses)

**Comment by deedey** [comment]
Hi Francesco !
To see your courses on mindmap you have to auto-assign these courses. If you have courses on your dashboard you can see them on mindmap. 
Regards
Dey

**Comment by francescor** [comment]
thanks for the quick reply 

we already have a lot of courses, and a lot (really a lot) of users: do you have any suggestion on how we can do it? (we have a testing version running, so feel free to suggest what you think can solve)

thanks

**Comment by deedey** [comment]
Please can you send me a screenshot of your dashboard ?
Mymindmap was tested on all versions 2.9 until 4.02

**Comment by francescor** [comment]
Hi, deedey, thank for your help!

here the dashboard 

![Screenshot from 2022-12-09 16-15-28](https://user-images.githubusercontent.com/424577/206733828-c7c727db-ae0e-404a-918f-3f98c03bc197.png)

**Comment by deedey** [comment]
Hi! francescor
I'm sorry to see that you didn't follow the instructions:
On the one hand, it must be on the Dashboard and not on "Home" because the programs to which Mindmap_Overview calls are located in the Dashboard domain.
In addition, it is necessary to set the block to "Content".
Regards
Dey
![2022-12-12_160802](https://user-images.githubusercontent.com/5656024/207080715-ae00aea3-532b-442c-a934-8d0a39e2267d.jpg)
![2022-12-12_160942](https://user-images.githubusercontent.com/5656024/207080718-c2582156-6f7d-45d2-97d1-0ef8535072e1.jpg)

**Comment by francescor** [comment]
yes [deedey](https://github.com/deedey) you are perfectly right!

now it works perfectly!

**Comment by deedey** [comment]
I"m glad to hear it Francescor.
Regards
Deedey

**Comment by francescor** [comment]
(thanks! for releasing the code, and for the prompt support!)
